2025-10-09 08:34:37,433 INFO    MainThread:36177 [wandb_setup.py:_flush():77] Current SDK version is 0.18.0
2025-10-09 08:34:37,433 INFO    MainThread:36177 [wandb_setup.py:_flush():77] Configure stats pid to 36177
2025-10-09 08:34:37,433 INFO    MainThread:36177 [wandb_setup.py:_flush():77] Loading settings from /home/david/.config/wandb/settings
2025-10-09 08:34:37,433 INFO    MainThread:36177 [wandb_setup.py:_flush():77] Loading settings from /home/david/Área de trabalho/projetos/NewVQVAE/wandb/settings
2025-10-09 08:34:37,434 INFO    MainThread:36177 [wandb_setup.py:_flush():77] Loading settings from environment variables: {'api_key': '***REDACTED***'}
2025-10-09 08:34:37,434 INFO    MainThread:36177 [wandb_setup.py:_flush():77] Applying setup settings: {'_disable_service': False}
2025-10-09 08:34:37,434 INFO    MainThread:36177 [wandb_setup.py:_flush():77] Inferring run settings from compute environment: {'program_relpath': 'Viewer.py', 'program_abspath': '/home/david/Área de trabalho/projetos/NewVQVAE/Viewer.py', 'program': '/home/david/Área de trabalho/projetos/NewVQVAE/Viewer.py'}
2025-10-09 08:34:37,434 INFO    MainThread:36177 [wandb_setup.py:_flush():77] Applying login settings: {}
2025-10-09 08:34:37,434 INFO    MainThread:36177 [wandb_init.py:_log_setup():525] Logging user logs to /home/david/Área de trabalho/projetos/NewVQVAE/wandb/run-20251009_083437-linziupe/logs/debug.log
2025-10-09 08:34:37,434 INFO    MainThread:36177 [wandb_init.py:_log_setup():526] Logging internal logs to /home/david/Área de trabalho/projetos/NewVQVAE/wandb/run-20251009_083437-linziupe/logs/debug-internal.log
2025-10-09 08:34:37,434 INFO    MainThread:36177 [wandb_init.py:init():609] calling init triggers
2025-10-09 08:34:37,434 INFO    MainThread:36177 [wandb_init.py:init():616] wandb.init called with sweep_config: {}
config: {'test': 1}
2025-10-09 08:34:37,434 INFO    MainThread:36177 [wandb_init.py:init():659] starting backend
2025-10-09 08:34:37,434 INFO    MainThread:36177 [wandb_init.py:init():663] setting up manager
2025-10-09 08:34:37,437 INFO    MainThread:36177 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-10-09 08:34:37,438 INFO    MainThread:36177 [wandb_init.py:init():671] backend started and connected
2025-10-09 08:34:37,441 INFO    MainThread:36177 [wandb_init.py:init():766] updated telemetry
2025-10-09 08:34:37,448 INFO    MainThread:36177 [wandb_init.py:init():799] communicating run to backend with 90.0 second timeout
2025-10-09 08:34:37,960 INFO    MainThread:36177 [wandb_init.py:init():850] starting run threads in backend
2025-10-09 08:34:38,205 INFO    MainThread:36177 [wandb_run.py:_console_start():2466] atexit reg
2025-10-09 08:34:38,205 INFO    MainThread:36177 [wandb_run.py:_redirect():2312] redirect: wrap_raw
2025-10-09 08:34:38,205 INFO    MainThread:36177 [wandb_run.py:_redirect():2377] Wrapping output streams.
2025-10-09 08:34:38,205 INFO    MainThread:36177 [wandb_run.py:_redirect():2402] Redirects installed.
2025-10-09 08:34:38,207 INFO    MainThread:36177 [wandb_init.py:init():893] run started, returning control to user process
2025-10-09 08:34:41,612 ERROR   MainThread:36177 [util.py:get_module():277] Error importing optional module moviepy.editor
Traceback (most recent call last):
  File "/home/david/miniconda3/envs/VQVAE/lib/python3.10/site-packages/wandb/util.py", line 243, in import_module_lazy
    return sys.modules[name]
KeyError: 'moviepy.editor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/david/miniconda3/envs/VQVAE/lib/python3.10/site-packages/wandb/util.py", line 272, in get_module
    return import_module_lazy(name)
  File "/home/david/miniconda3/envs/VQVAE/lib/python3.10/site-packages/wandb/util.py", line 247, in import_module_lazy
    raise ModuleNotFoundError
ModuleNotFoundError
2025-10-09 08:34:41,617 WARNING MsgRouterThr:36177 [router.py:message_loop():77] message_loop has been closed
