Traceback (most recent call last):
  File "/home/david/miniconda3/envs/VQVAE/lib/python3.10/site-packages/PIL/Image.py", line 3311, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 24), '<f8')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/david/Área de trabalho/projetos/NewVQVAE/Viewer.py", line 161, in <module>
    Viewer.saveTensorAsGIF(video0,"control","trainVideo")
  File "/home/david/Área de trabalho/projetos/NewVQVAE/Viewer.py", line 138, in saveTensorAsGIF
    imageio.mimsave(gif_path, frames, fps=fps)
  File "/home/david/miniconda3/envs/VQVAE/lib/python3.10/site-packages/imageio/v2.py", line 495, in mimwrite
    return file.write(ims, is_batch=True, **kwargs)
  File "/home/david/miniconda3/envs/VQVAE/lib/python3.10/site-packages/imageio/plugins/pillow.py", line 444, in write
    pil_frame = Image.fromarray(frame, mode=mode)
  File "/home/david/miniconda3/envs/VQVAE/lib/python3.10/site-packages/PIL/Image.py", line 3315, in fromarray
    raise TypeError(msg) from e
TypeError: Cannot handle this data type: (1, 1, 24), <f8
Traceback (most recent call last):
  File "/home/david/miniconda3/envs/VQVAE/lib/python3.10/site-packages/PIL/Image.py", line 3311, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 24), '<f8')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/david/Área de trabalho/projetos/NewVQVAE/Viewer.py", line 161, in <module>
    Viewer.saveTensorAsGIF(video0,"control","trainVideo")
  File "/home/david/Área de trabalho/projetos/NewVQVAE/Viewer.py", line 138, in saveTensorAsGIF
    imageio.mimsave(gif_path, frames, fps=fps)
  File "/home/david/miniconda3/envs/VQVAE/lib/python3.10/site-packages/imageio/v2.py", line 495, in mimwrite
    return file.write(ims, is_batch=True, **kwargs)
  File "/home/david/miniconda3/envs/VQVAE/lib/python3.10/site-packages/imageio/plugins/pillow.py", line 444, in write
    pil_frame = Image.fromarray(frame, mode=mode)
  File "/home/david/miniconda3/envs/VQVAE/lib/python3.10/site-packages/PIL/Image.py", line 3315, in fromarray
    raise TypeError(msg) from e
TypeError: Cannot handle this data type: (1, 1, 24), <f8
