2025-10-08 14:36:59,847 INFO    MainThread:17045 [wandb_setup.py:_flush():77] Current SDK version is 0.18.0
2025-10-08 14:36:59,847 INFO    MainThread:17045 [wandb_setup.py:_flush():77] Configure stats pid to 17045
2025-10-08 14:36:59,847 INFO    MainThread:17045 [wandb_setup.py:_flush():77] Loading settings from /home/david/.config/wandb/settings
2025-10-08 14:36:59,847 INFO    MainThread:17045 [wandb_setup.py:_flush():77] Loading settings from /home/david/Área de trabalho/projetos/NewVQVAE/wandb/settings
2025-10-08 14:36:59,847 INFO    MainThread:17045 [wandb_setup.py:_flush():77] Loading settings from environment variables: {}
2025-10-08 14:36:59,847 INFO    MainThread:17045 [wandb_setup.py:_flush():77] Applying setup settings: {'_disable_service': False}
2025-10-08 14:36:59,847 INFO    MainThread:17045 [wandb_setup.py:_flush():77] Inferring run settings from compute environment: {'program_relpath': 'Viewer.py', 'program_abspath': '/home/david/Área de trabalho/projetos/NewVQVAE/Viewer.py', 'program': '/home/david/Área de trabalho/projetos/NewVQVAE/Viewer.py'}
2025-10-08 14:36:59,847 INFO    MainThread:17045 [wandb_setup.py:_flush():77] Applying login settings: {}
2025-10-08 14:36:59,848 INFO    MainThread:17045 [wandb_init.py:_log_setup():525] Logging user logs to /home/david/Área de trabalho/projetos/NewVQVAE/wandb/run-20251008_143659-cyyl0lrx/logs/debug.log
2025-10-08 14:36:59,848 INFO    MainThread:17045 [wandb_init.py:_log_setup():526] Logging internal logs to /home/david/Área de trabalho/projetos/NewVQVAE/wandb/run-20251008_143659-cyyl0lrx/logs/debug-internal.log
2025-10-08 14:36:59,848 INFO    MainThread:17045 [wandb_init.py:init():609] calling init triggers
2025-10-08 14:36:59,848 INFO    MainThread:17045 [wandb_init.py:init():616] wandb.init called with sweep_config: {}
config: {'test': 1}
2025-10-08 14:36:59,848 INFO    MainThread:17045 [wandb_init.py:init():659] starting backend
2025-10-08 14:36:59,848 INFO    MainThread:17045 [wandb_init.py:init():663] setting up manager
2025-10-08 14:36:59,850 INFO    MainThread:17045 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-10-08 14:36:59,860 INFO    MainThread:17045 [wandb_init.py:init():671] backend started and connected
2025-10-08 14:36:59,863 INFO    MainThread:17045 [wandb_init.py:init():766] updated telemetry
2025-10-08 14:36:59,870 INFO    MainThread:17045 [wandb_init.py:init():799] communicating run to backend with 90.0 second timeout
2025-10-08 14:37:00,251 ERROR   MainThread:17045 [wandb_init.py:init():825] encountered error: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-10-08 14:37:00,251 ERROR   MainThread:17045 [wandb_init.py:init():1244] error in wandb.init()
Traceback (most recent call last):
  File "/home/david/miniconda3/envs/VQVAE/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1234, in init
    return wi.init()
  File "/home/david/miniconda3/envs/VQVAE/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 831, in init
    raise error
wandb.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-10-08 14:37:01,512 WARNING MsgRouterThr:17045 [router.py:message_loop():77] message_loop has been closed
